/**
 * 今日爆品热点库（人工监测 + 公开趋势整理）
 * 每日 8:00 轮换排序；换一批切换 batch 展示不同顺序。
 * 生产环境可接定时任务 / AI 抓取替换本库。
 */

export type HotTopicSeed = {
  title: string;
  desc: string;
  heat: "爆" | "高" | "中";
  track: string;
  format: string;
  sources: ("抖音" | "小红书" | "视频号")[];
  /** 可借鉴的爆点角度 */
  angle: string;
};

/** 2026-05-22 监测整理（抖音热搜风向、小红书笔记趋势、视频号私域爆款结构） */
export const HOT_TOPICS_POOL: HotTopicSeed[] = [
  {
    title: "打工人周三能量低谷",
    desc: "周中倦怠共鸣，适合轻干货+情绪接住",
    heat: "高",
    track: "职场成长",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "反内耗三招，今晚就能拍",
  },
  {
    title: "多巴胺穿搭上镜公式",
    desc: "高饱和配色+简单转场，穿搭号易拿自然流量",
    heat: "爆",
    track: "个人IP",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "一套配色模板直接跟拍",
  },
  {
    title: "薄荷绿饮品清爽测评",
    desc: "茶饮视觉清爽风回流，适合探店/测评号",
    heat: "高",
    track: "本地生活",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "对比3家同款，评论区吵起来",
  },
  {
    title: "春季养宠换季护理清单",
    desc: "宠物博主清单图文，收藏率高",
    heat: "高",
    track: "宠物博主",
    format: "图文",
    sources: ["小红书", "视频号"],
    angle: "7条注意事项，结尾留问句",
  },
  {
    title: "本地门店周末引流三板斧",
    desc: "探店+限时福利话术，适合同城号",
    heat: "高",
    track: "本地生活",
    format: "短视频",
    sources: ["抖音", "视频号"],
    angle: "到店福利+预约钩子",
  },
  {
    title: "小红书封面3秒停留法则",
    desc: "封面字大+反差标题，运营干货常青",
    heat: "中",
    track: "小红书运营",
    format: "图文",
    sources: ["小红书"],
    angle: "前后封面对比案例",
  },
  {
    title: "视频号熟人信任型起号",
    desc: "专业人设+案例拆解，适合35+客群",
    heat: "高",
    track: "个人IP",
    format: "口播",
    sources: ["视频号"],
    angle: "一条视频讲清你能帮谁",
  },
  {
    title: "普通人副业起号第一周",
    desc: "反焦虑起号清单，低粉也能发",
    heat: "爆",
    track: "个人IP",
    format: "口播",
    sources: ["抖音", "小红书", "视频号"],
    angle: "每天只发1条也能坚持",
  },
  {
    title: "情感账号高互动首评模板",
    desc: "预埋神评论，拉升互动率",
    heat: "中",
    track: "婚恋情感",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "结尾提问+首评引导",
  },
  {
    title: "宝妈早起1小时自律日常",
    desc: "真实日程+vlog切片，母婴号易共鸣",
    heat: "高",
    track: "母婴育儿",
    format: "短视频",
    sources: ["小红书", "视频号"],
    angle: "不贩卖焦虑，只晒可抄作业",
  },
  {
    title: "学生党宿舍低成本护肤",
    desc: "平价好物合集，学生赛道稳定流量",
    heat: "中",
    track: "美妆护肤",
    format: "图文",
    sources: ["抖音", "小红书"],
    angle: "总价不过百清单",
  },
  {
    title: "电商带货直播间憋单话术",
    desc: "限时+库存紧张节奏，适合带货号",
    heat: "高",
    track: "电商带货",
    format: "直播切片",
    sources: ["抖音"],
    angle: "3句逼单不违规版",
  },
  {
    title: "职场反PUA沟通一句封神",
    desc: "情景剧+字幕金句，易转发",
    heat: "爆",
    track: "职场成长",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "领导这样说你就回",
  },
  {
    title: "减脂期外卖怎么点",
    desc: "实用攻略型，健康赛道收藏多",
    heat: "高",
    track: "健身减脂",
    format: "图文",
    sources: ["小红书"],
    angle: "麦当劳/麻辣烫对照表",
  },
  {
    title: "租房避坑10条血泪总结",
    desc: "年轻人刚需话题，评论讨论热烈",
    heat: "高",
    track: "生活干货",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "中介不会告诉你的细节",
  },
  {
    title: "AI工具帮写短视频脚本",
    desc: "效率工具向，创作者搜索量上涨",
    heat: "爆",
    track: "个人IP",
    format: "口播",
    sources: ["抖音", "小红书", "视频号"],
    angle: "演示1分钟出稿过程",
  },
  {
    title: "火锅店排队氛围感拍摄",
    desc: "本地餐饮视觉爆款结构",
    heat: "中",
    track: "本地生活",
    format: "短视频",
    sources: ["抖音"],
    angle: "镜头节奏+BGM卡点",
  },
  {
    title: "本命年红色穿搭不显土",
    desc: "节日节点+穿搭教程",
    heat: "高",
    track: "个人IP",
    format: "图文",
    sources: ["小红书"],
    angle: "3套日常可穿方案",
  },
  {
    title: "情侣冷战怎么破冰",
    desc: "情绪聊天向延伸，情感号刚需",
    heat: "高",
    track: "婚恋情感",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "先发情绪再接话",
  },
  {
    title: "短视频前3秒钩子合集",
    desc: "培训向干货，适合运营教学号",
    heat: "爆",
    track: "小红书运营",
    format: "口播",
    sources: ["抖音", "小红书", "视频号"],
    angle: "5个钩子模板直接念",
  },
  {
    title: "幼儿园入园焦虑怎么聊",
    desc: "家长群高频话题，共鸣强",
    heat: "中",
    track: "母婴育儿",
    format: "口播",
    sources: ["视频号", "小红书"],
    angle: "老师视角+家长视角",
  },
  {
    title: "618预售规则一次讲懂",
    desc: "节点营销，电商号时效性强",
    heat: "高",
    track: "电商带货",
    format: "图文",
    sources: ["抖音", "小红书"],
    angle: "省钱计算器演示",
  },
  {
    title: "沉浸式收纳治愈解压",
    desc: "治愈系易完播，家居号友好",
    heat: "中",
    track: "生活干货",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "原声+快进节奏",
  },
  {
    title: "律师普法人人都关心",
    desc: "知识信任型，适合专业人设",
    heat: "高",
    track: "个人IP",
    format: "口播",
    sources: ["视频号", "抖音"],
    angle: "一个案例讲清风险",
  },
  {
    title: "探店人均50宝藏小馆",
    desc: "性价比探店，本地流量稳定",
    heat: "高",
    track: "本地生活",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "人均+必点三样",
  },
  {
    title: "婚礼跟拍避坑指南",
    desc: "高客单行业种草向",
    heat: "中",
    track: "婚恋情感",
    format: "图文",
    sources: ["小红书"],
    angle: "样片对比+合同条款",
  },
  {
    title: "健身新手一周训练计划",
    desc: "跟练类收藏高，运动号拉粉",
    heat: "高",
    track: "健身减脂",
    format: "短视频",
    sources: ["抖音"],
    angle: "无器械版跟练",
  },
  {
    title: "短视频运营日更还是质量",
    desc: "创作者争议话题，评论活跃",
    heat: "爆",
    track: "个人IP",
    format: "口播",
    sources: ["抖音", "小红书", "视频号"],
    angle: "给出你的明确立场",
  },
  {
    title: "图文笔记九宫格排版",
    desc: "小红书技能型常青内容",
    heat: "中",
    track: "小红书运营",
    format: "图文",
    sources: ["小红书"],
    angle: "模板直接套",
  },
  {
    title: "银发族手机防骗提醒",
    desc: "视频号家庭群易转发",
    heat: "高",
    track: "生活干货",
    format: "口播",
    sources: ["视频号"],
    angle: "子女转给父母版",
  },
  {
    title: "露营轻装备入门清单",
    desc: "季节户外话题回暖",
    heat: "中",
    track: "生活干货",
    format: "图文",
    sources: ["抖音", "小红书"],
    angle: "总价500内方案",
  },
  {
    title: "美妆博主素颜底气妆",
    desc: "真实感+教程，信任度高",
    heat: "高",
    track: "美妆护肤",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "前后对比不夸张",
  },
  {
    title: "知识博主如何做系列化",
    desc: "提升关注转化的结构干货",
    heat: "高",
    track: "个人IP",
    format: "口播",
    sources: ["视频号", "抖音"],
    angle: "三部曲连载预告",
  },
  {
    title: "奶茶店联名款值不值得买",
    desc: "测评争议型，讨论量高",
    heat: "爆",
    track: "本地生活",
    format: "短视频",
    sources: ["抖音", "小红书"],
    angle: "打分+排队时长",
  },
  {
    title: "体制内穿搭低调高级",
    desc: "职场细分人群精准",
    heat: "中",
    track: "职场成长",
    format: "图文",
    sources: ["小红书"],
    angle: "5套一周不重样",
  },
  {
    title: "宠物拆家怎么办",
    desc: "痛点+解决方案，宠物号刚需",
    heat: "高",
    track: "宠物博主",
    format: "口播",
    sources: ["抖音", "小红书"],
    angle: "原因分析+3步训练",
  },
  {
    title: "口播提词不尴尬技巧",
    desc: "新手创作者搜索高频",
    heat: "高",
    track: "个人IP",
    format: "口播",
    sources: ["抖音", "视频号"],
    angle: "眼神看镜头演示",
  },
];

export const HOT_TOPICS_POOL_SIZE = HOT_TOPICS_POOL.length;
