import type { HotTopicInsert } from "@/lib/server/db/hot-topics-db";
import { coverForCategory } from "@/lib/hot-topics/category-covers";

/** 数据库为空时的默认热点（seed 入库，非前端写死） */
export function buildMockHotTopicRows(batchDate: string): HotTopicInsert[] {
  const seeds = [
    {
      raw: "多巴胺穿搭",
      display: "多巴胺穿搭上镜公式",
      summary:
        "最近多巴胺穿搭类内容热度较高，适合穿搭号、生活号、小红书种草号切入，普通人可以用颜色搭配和上镜技巧做内容。",
      platform: "douyin",
      heat: 951000,
      category: "穿搭",
      viral: 91,
      tags: ["穿搭", "小红书", "上镜", "普通人"],
      users: ["穿搭号", "生活号", "学生党", "小红书种草"],
      angles: ["上镜公式", "配色技巧", "普通人穿搭", "拍照姿势"],
    },
    {
      raw: "AI工具",
      display: "AI工具帮写短视频脚本",
      summary: "AI 效率工具向内容搜索量上涨，适合职场号、成长号用实操演示切入。",
      platform: "zhihu",
      heat: 820000,
      category: "AI工具",
      viral: 83,
      tags: ["AI", "脚本", "效率", "创作者"],
      users: ["职场号", "成长号", "副业号"],
      angles: ["3步写脚本", "工具对比", "新手教程"],
    },
    {
      raw: "下班后生活",
      display: "下班后的治愈时刻",
      summary: "治愈系日常 vlog 持续有流量，适合情感号、生活号用真实下班场景拍摄。",
      platform: "weibo",
      heat: 880000,
      category: "治愈",
      viral: 85,
      tags: ["治愈", "vlog", "下班", "生活"],
      users: ["情感号", "生活号", "Vlog号"],
      angles: ["一人食", "房间氛围", "周末小确幸"],
    },
    {
      raw: "宠物日常",
      display: "猫咪治愈瞬间",
      summary: "萌宠内容收藏率高，适合宠物号用短平快治愈画面切入。",
      platform: "douyin",
      heat: 760000,
      category: "宠物",
      viral: 82,
      tags: ["宠物", "猫咪", "治愈"],
      users: ["宠物号", "萌宠号"],
      angles: ["萌宠日常", "互动玩法", "治愈瞬间"],
    },
    {
      raw: "年轻人存钱",
      display: "普通人的30天改变",
      summary: "成长反差类选题容易引发共鸣，适合副业号、职场号记录真实变化。",
      platform: "bilibili",
      heat: 690000,
      category: "成长",
      viral: 78,
      tags: ["成长", "存钱", "反差"],
      users: ["成长号", "副业号", "职场号"],
      angles: ["30天记录", "前后对比", "真实账本"],
    },
    {
      raw: "职场效率",
      display: "打工人效率提升3招",
      summary: "职场干货 evergreen，适合口播+清单结构快速产出。",
      platform: "toutiao",
      heat: 620000,
      category: "职场",
      viral: 76,
      tags: ["职场", "干货", "打工人"],
      users: ["职场号", "成长号"],
      angles: ["清单体", "反内耗", "时间管理"],
    },
    {
      raw: "本地探店",
      display: "人均50宝藏小店",
      summary: "探店+性价比是同城号稳定流量结构，今天就能拍。",
      platform: "douyin",
      heat: 580000,
      category: "探店",
      viral: 74,
      tags: ["探店", "本地生活", "美食"],
      users: ["探店号", "美食号", "生活号"],
      angles: ["对比测评", "到店福利", "避坑指南"],
    },
    {
      raw: "学生党学习",
      display: "学生党高效学习法",
      summary: "开学季学习打卡内容易获收藏，适合学生向账号。",
      platform: "bilibili",
      heat: 540000,
      category: "学生",
      viral: 72,
      tags: ["学生", "学习", "干货"],
      users: ["学生号", "成长号"],
      angles: ["学习vlog", "备考清单", "桌面改造"],
    },
    {
      raw: "宝妈日常",
      display: "宝妈一天真实记录",
      summary: "宝妈共鸣内容互动率高，适合真实育儿日常切入。",
      platform: "weibo",
      heat: 510000,
      category: "宝妈",
      viral: 71,
      tags: ["宝妈", "育儿", "日常"],
      users: ["宝妈号", "生活号"],
      angles: ["真实一天", "育儿清单", "情绪共鸣"],
    },
    {
      raw: "副业思路",
      display: "普通人副业3个方向",
      summary: "副业话题搜索稳定，适合口播+案例拆解。",
      platform: "zhihu",
      heat: 480000,
      category: "副业",
      viral: 70,
      tags: ["副业", "搞钱", "普通人"],
      users: ["副业号", "职场号"],
      angles: ["真实案例", "避坑", "从0开始"],
    },
  ];

  return seeds.map((s, i) => ({
    raw_title: s.raw,
    display_title: s.display,
    summary: s.summary,
    platform: s.platform,
    heat_value: `${(s.heat / 10000).toFixed(1)}w`,
    heat_score: s.heat,
    cover_image: coverForCategory(s.category),
    category: s.category,
    tags: s.tags,
    target_users: s.users,
    recommend_angles: s.angles,
    viral_score: s.viral,
    source_url: null,
    is_new: i < 3,
    status: "active" as const,
    updated_batch_date: batchDate,
  }));
}
